import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import FavIcon from "../../public/favicon-argenpesos.svg"


export const metadata: Metadata = {
  title: "Argenpesos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="gotham">
      <head>
        <link rel="icon" href={FavIcon} />
      </head>
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
